require ***------ permissions on all files

diff --git a/pw b/pw
--- a/pw
+++ b/pw
@@ -16,8 +16,23 @@ add_safedir() {
 }
 
 make_safedir_config() {
+    old_umask=$(umask)
+    umask 0077
     echo '# put full paths to safe directories here' >"$safedir_config"
+    umask $old_umask
     add_safedir
+}
+
+make_config() {
+    old_umask=$(umask)
+    umask 0077
+    mkdir -p "$config" || die 1 "Can't make $config"
+    umask $old_umask
+}
+
+require_private() {
+    ls -ld "$1" | awk '{print $1}' | grep -e '------$' >/dev/null \
+    || die 1 "$1 should be not be readable or writable by others"
 }
 
 my_dialog() {
@@ -37,13 +52,14 @@ my_dialog() {
 USAGE="$0 [-u] [-url]"
 
 config="$HOME/.config/pw"
-test -d "$config" || mkdir -p "$config" || die 1 "Can't make $config"
+test -d "$config" || make_config
 
 safedir_config="$config/safedir"
 
 while [ ! -f "$safedir_config" ]; do
     make_safedir_config
 done
+require_private "$safedir_config"
 
 safedirs="$(grep -v '^#' "$safedir_config")"
 
@@ -113,6 +129,10 @@ test $# -eq 1 && request="$1"
 #done } |\
 
 #my_dialog
+
+for i in "$config" "$safedir_config" "$safedirs" "$safedirs/"*; do
+    require_private "$i"
+done
 
 grep -v -h '^#' "$safedirs/"* |\
 grep $ignore_case $request |\
